import typer from 'typer-js'
import { demoItemChange } from 'actions'
export default lineDemo

function lineDemo(dispatch, index) {
  typer('#explanation .container')
    .line(`Now let's <span class="i">really</span> dig in to <span class="lime">Typer.js</span>!`)
    .pause(1000)
    .back('all', 10)
    .continue('Introducing the <span class="lime">line</span> method:')
    .emit('line-1')
    .listen('line-2')
    .pause(1000)
    .back('all', 10)
    .continue('As you can see, <span class="lime">line</span> takes 2 arguments.')
    .pause(1000)
    .back('all', 10)
    .continue(`The 1st argument is a string.`)
    .pause()
    .line(`This is what will be typed out.`)
    .pause()
    .line(`The 2nd argument (optional) is a number.`)
    .pause()
    .line(`That's the typing speed:`)
    .pause()
    .continue(` ms per character.`)
    .pause(1200)
    .empty()
    .continue(`The higher the number, the slower the typing.`)
    .pause(1000)
    .back('all', 10)
    .continue(`Notice how things are typed out letter-by-letter.`)
    .pause(1200)
    .back('all', 10)
    .continue(`If you provide an array for the 1st argument,`)
    .emit('line-3')
    .listen('line-4')
    .line(['things', ' are', ' typed', ' out', ' word-', 'by-', 'word.'], 500)
    .pause(1500)
    .empty()
    .continue([`You can type a whole line at once like this:`])
    .pause()
    .emit('line-5')
    .listen('line-6')
    .pause(1500)
    .empty()
    .continue(`So we've seen the 1st argument can be:`)
    .line(`* a string - letter-by-letter typing`)
    .pause()
    .line(`* an array - `)
    .continue(['word-', 'by-', 'word'], 500)
    .pause()
    .continue(' typing')
    .pause(1200)
    .empty()
    .continue(`And we've seen the 2nd argument is a number.`)
    .emit('line-6a')
    .pause()
    .line(`This controls how fast the typing occurs.`)
    .pause(1200)
    .empty()
    .continue(`Now let's get <span class="i">real</span> fancy...`)
    .emit('line-7')
    .listen('line-8')
    .pause()
    .back('all', 10)
    .continue(`We can pass an options object to the 2nd argument`)
    .line(`and do some very neat <span class="i">speed</span> related things!`)
    .pause(1500)
    .empty()
    .continue(`In the example below, we've declared the <span class="mono">speed</span> property.`)
    .pause()
    .line(`This behaves the same as when we passed in a number.`)
    .pause(1000)
    .empty()
    .continue('Not so fancy?')
    .pause()
    .continue(` How 'bout <span class="i">this</span>:`)
    .emit('line-9')
    .listen('line-10')
    .line('humanized typing!')
    .pause(1000)
    .empty()
    .continue('When providing the <span class="mono">min</span> & <span class="mono">max</span> properties,')
    .line(`we're telling <span class="lime">line</span> to pick a random number between the two`)
    .line(`for each letter and use it as the speed!`)
    .pause(1200)
    .empty()
    .continue('The result?')
    .pause()
    .line(`You get humanized typing that looks <span class="i">soooo</span> real!`, { min: 30, max: 350 })
    .pause(1000)
    .empty()
    .continue(`We've got another speed trick up our sleeve:`)
    .emit('line-11')
    .listen('line-12')
    .line([`<span class="mono">totalTime</span>!`], 1)
    .pause(1200)
    .empty()
    .continue(`The <span class="mono">totalTime</span> property declares`)
    .line(`<span class="i">how long</span> typing the line should take.`)
    .pause()
    .line(`The example below will take 3 seconds to type.`)
    .pause(1000)
    .empty()
    .continue(`Are you standing?`)
    .pause()
    .continue(` Well sit down, we're not done.`)
    .pause()
    .back('all', 10)
    .continue(`The <span class="lime">line</span> method processes your content`)
    .line(`as <span class="i">html</span> by default.`)
    .pause()
    .line('For instance:')
    .emit('line-13')
    .listen('line-14')
    .pause(1000)
    .empty()
    .continue(`This will produce a span within the contents.`)
    .pause(1000)
    .back('all', 10)
    .continue(`If you don't want html to be produced,`)
    .line(`you must specify <span class="i">not</span> to:`)
    .emit('line-15')
    .listen('line-16')
    .pause(1000)
    .empty()
    .continue(`Providing <span class="mono">html<span class="mediumorchid">: false</span></span> will ensure that the`)
    .line(`contents are typed out exactly as you provide them.`)
    .pause(1500)
    .empty()
    .continue(`By default, <span class="lime">line</span> will type contents`)
    .line(`inside a fresh <span class="mono"><span class="deeppink"><</span>div<span class="deeppink">></span></span>.`)
    .pause()
    .line(`But you can specify a different element like so:`)
    .emit('line-17')
    .listen('line-18')
    .pause(1000)
    .empty()
    .continue(`We've just instructed <span class="lime">line</span> to create a`)
    .line(`<span class="mono"><span class="deeppink"><</span>span<span class="deeppink">></span></span> to type all our contents in.`)
    .pause(1500)
    .empty()
    .continue(`So far we've been talking about the options object`)
    .line(`as the <span class="i">2nd</span> argument to <span class="lime">line</span>.`)
    .pause()
    .line(`But there's something special we can achieve by`)
    .line(`using it as the <span class="i">1st</span> (and <span class="i">only</span>) argument...`)
    .pause(1500)
    .empty()
    .continue(`Imagine for a minute that you have a hidden`)
    .line(`element on the page with some content:`)
    .emit('line-19')
    .listen('line-20')
    .pause(1500)
    .empty()
    .continue('This content can still be indexed by search engines.')
    .pause()
    .line('<span class="b i">SEO</span> in the house!')
    .pause(1200)
    .empty()
    .continue(`We can use this hidden element to <span class="i">"feed"</span>`)
    .line(`<span class="lime">line</span> the content it needs to type.`)
    .line(`while still being SEO friendly.`)
    .pause(1500)
    .empty()
    .continue(`So how do we do it?`)
    .pause()
    .line(`Glad you asked :)`)
    .pause(1000)
    .empty()
    .continue(`This is where the options object as the`)
    .line(`<span class="i">1st</span> (and <span class="i">only</span>) argument comes in:`)
    .emit('line-21')
    .listen('line-22')
    .pause(1500)
    .empty()
    .continue(`By providing the <span class="mono">container</span> property,`)
    .line(`<span class="lime">line</span> will use that element to obtain its contents.`)
    .pause(1200)
    .empty()
    .continue(`When using the options object as the 1st argument`)
    .line(`you <span class="i">must</span> provide the <span class="mono">container</span> property.`)
    .pause()
    .line(`You can pass it a CSS selector or DOM node.`)
    .pause(1000)
    .empty()
    .continue('All the other options remain the same:')
    .emit('line-23')
    .listen('line-24')
    .run(() => dispatch(demoItemChange(index + 1)))

  const previousExampleContents1 = [
    `typer(<span class="yellow">'.someClass'</span>, <span class="mediumorchid">100</span>)`
  ]
  const previousExampleContents2 = [
    `  .cursor({ block<span class="mediumorchid">: true</span>`,
    `, blink<span class="mediumorchid">:</span> <span class="yellow">'hard'</span> })`
  ].join('')

  typer('#example .container', 40)
    .cursor({ block: true, blink: 'hard' })
    .line(previousExampleContents1, 1)
    .line([previousExampleContents2], 1)
    .listen('line-1')
    .line(`  .line(<span class="yellow">'Typer.js rules!'</span>, <span class="mediumorchid">100</span>)`)
    .emit('line-2')
    .listen('line-3')
    .back(-8, 10)
    .continue(`[<span class="yellow">'Typer.js'</span>, <span class="yellow">' rules!'</span>])`)
    .emit('line-4')
    .listen('line-5')
    .back(-8, 10)
    .continue(`[<span class="yellow">'This sentence will be typed all at once!'</span>])`)
    .emit('line-6')
    .listen('line-6a')
    .back(1, 10)
    .continue(', <span class="mediumorchid">100</span>)')
    .listen('line-7')
    .back(-8, 10)
    .continue(`<span class="yellow">'Typer.js rules!'</span>, { speed<span class="mediumorchid">: 100</span> })`)
    .emit('line-8')
    .listen('line-9')
    .back(13, 10)
    .continue('min<span class="mediumorchid">: 30</span>, max<span class="mediumorchid">: 350</span> })')
    .emit('line-10')
    .listen('line-11')
    .back(20, 10)
    .continue('totalTime<span class="mediumorchid">: 3000</span> })')
    .emit('line-12')
    .listen('line-13')
    .back(-8, 10)
    .continue(`<span class="yellow">'I have &lt;span class="italic"&gt;html&lt;/span&gt; content'</span>)`)
    .emit('line-14')
    .listen('line-15')
    .back(1, 10)
    .continue(`, { html<span class="mediumorchid">: false</span> })`)
    .pause()
    .emit('line-16')
    .listen('line-17')
    .back(14, 10)
    .continue(`element: <span class="yellow">'span'</span> })`)
    .emit('line-18')
    .listen('line-19')
    .empty()
    .continue(`&lt;<span class="deeppink">div</span> <span class="lime">class</span>=<span class="yellow">"content"</span> <span class="lime">style</span>=<span class="yellow">"</span><span class="i darkturquoise">display</span>: <span class="darkturquoise">none</span>;<span class="yellow">"</span>&gt;`, 10)
    .line(`  Search engines can see this content!`, 10)
    .line(`&lt;/<span class="deeppink">div</span>&gt;`, 10)
    .emit('line-20')
    .listen('line-21')
    .line()
    .line(previousExampleContents1[0])
    .line(`  .line({ container<span class="mediumorchid">:</span> <span class="yellow">'.content'</span> })`)
    .emit('line-22')
    .listen('line-23')
    .back(3, 10)
    .continue(`, speed<span class="mediumorchid">: 100</span> })`)
    .pause(1000)
    .back(-33, 10)
    .continue(`min<span class="mediumorchid">: 30</span>, max<span class="mediumorchid">: 350</span> })`)
    .pause(1000)
    .back(-33, 10)
    .continue(`element<span class="mediumorchid">:</span> <span class="yellow">'span'</span> })`)
    .pause(1000)
    .back(3, 10)
    .continue(`, html<span class="mediumorchid">: false</span> })`)
    .pause(2000)
    .emit('line-24')
}
